// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	auth.proto
	common.proto
	conf.proto
	friend.proto
	login.proto
	pvp.proto
	server.proto

It has these top-level messages:
	UserInfo
	UserRoleInfo
	LogicServerInfo
	Vec2
	Vec3
	ServerTime
	ServerTimeC2S
	TimeRecord
	NumberRecord
	GamerId
	Gamer
	GamerMini
	GamerRecharge
	PlayerSpeciality
	Player
	GamerProxy
	Mail
	FriendRequest
	BlackGamer
	ItemConfig
	Effect
	CritPara
	SdVector2
	PropertyValue
	SpecialityInitPool
	PveNpcDate
	AiAreaDescrip
	AiAreaDescripConfig
	AnimationSmooth
	AnimationSmoothConfig
	BallPosition
	BallPositionConfig
	BattleParameter
	BattleParameterConfig
	CostAll
	CostAllConfig
	CourtTimeParameter
	CourtTimeParameterConfig
	DropMatching
	DropMatchingConfig
	FightConstParameter
	FightConstParameterConfig
	FragmentCompound
	FragmentCompoundConfig
	ItemBase
	ItemBaseConfig
	Locale
	LocaleConfig
	NpcMain
	NpcMainConfig
	PlayerModel
	PlayerModelConfig
	PlayerProperty
	PlayerPropertyConfig
	PlayerPropertyQuality
	PlayerPropertyQualityConfig
	PlayerSelect
	PlayerSelectConfig
	PlayerSelectPackage
	PlayerSelectPackageConfig
	PlayerSelectPackWeight
	PlayerSelectPackWeightConfig
	PlayerSkillBase
	PlayerSkillBaseConfig
	PlayerSkillConstantPara
	PlayerSkillConstantParaConfig
	PlayerSkillEffect
	PlayerSkillEffectConfig
	PlayerSkillLvUp
	PlayerSkillLvUpConfig
	PveChapter
	PveChapterConfig
	PvpPos
	PvpPosConfig
	ResourcesImg
	ResourcesImgConfig
	SceneModel
	SceneModelConfig
	SdKeyMapping
	SdKeyMappingConfig
	SdNameLibrary
	SdNameLibraryConfig
	SdPlayerAction
	SdPlayerActionConfig
	SdPlayerEmoji
	SdPlayerEmojiConfig
	SdPlayerEnergy
	SdPlayerEnergyConfig
	SdPlayerLvUp
	SdPlayerLvUpConfig
	SdPlayerLvUpProperty
	SdPlayerLvUpPropertyConfig
	SdPlayerMain
	SdPlayerMainConfig
	SdPlayerPosition
	SdPlayerPositionConfig
	SdPlayerProperty
	SdPlayerPropertyConfig
	SdPlayerSchool
	SdPlayerSchoolConfig
	SpecialityConfig
	SpecialityConfigConfig
	SpecialityPackage
	SpecialityPackageConfig
	SpecialityPoolWeight
	SpecialityPoolWeightConfig
	TeamInit
	TeamInitConfig
	ThrowerInPosition
	ThrowerInPositionConfig
	TrainingAi
	TrainingAiConfig
	TrainingNpc
	TrainingNpcConfig
	TrainingSection
	TrainingSectionConfig
	Friend
	GamerAddFriendC2S
	GamerGetFriendRequestC2S
	GamerGetFriendRequestS2C
	GamerDealFriendRequestC2S
	GamerDealFriendRequestS2C
	GamerClearFriendRequestC2S
	GamerGetAllFriendC2S
	GamerGetAllFriendS2C
	GamerDelFriendC2S
	GamerDelFriendS2C
	GamerOwnerPlayerC2S
	GamerOwnerPlayerS2C
	GamerBuyPlayerC2S
	GamerBuyPlayerS2C
	GamerGetPackC2S
	GamerGetPackS2C
	GamerUseGoodsC2S
	GamerUseGoodsS2C
	GamerSellGoodsC2S
	GamerSellGoodsS2C
	FastReconnC2S
	GamerEmployPlayerC2S
	GamerEmployPlayerS2C
	GamerPlayerLvC2S
	GamerPlayerLvS2C
	GamerPlayerBreadthroughC2S
	GamerPlayerBreadthroughS2C
	GamerGetMailC2S
	GamerGetMailS2C
	GamerDelMailC2S
	GamerDelMailS2C
	GamerReceiveAttachmentC2S
	GamerReceiveAttachmentS2C
	GamerReadMailC2S
	GamerSetSignC2S
	GamerSetIconC2S
	GamerGetPlayerSpecialityC2S
	GamerGetPlayerSpecialityS2C
	GamerUpdatePlayerSpecialityC2S
	GamerUpdatePlayerSpecialityS2C
	GamerDailySignInC2C
	GamerDailySignInS2C
	GamerRemedySignInC2C
	GamerRemedySignInS2C
	GamerTotalSignInC2C
	GamerTotalSignInS2C
	GamerLoginC2S
	GamerLoginS2C
	PVPPlayer
	PVPMatchInfo
	GamerStartPVPMatchC2S
	GamerStartPVPMatchL2M
	NotifyGamerPVPMatch
	GamerInputChangePlayer
	GamerInput
	GamerPVPResult
	GamerPVPSyncC2S
	ServerInfo
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInfo struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Passwd           *string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
	Id               *string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserInfo) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func (m *UserInfo) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type UserRoleInfo struct {
	Id               *int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Server           *int32  `protobuf:"varint,3,opt,name=server" json:"server,omitempty"`
	Ctime            *int64  `protobuf:"varint,4,opt,name=ctime" json:"ctime,omitempty"`
	Uid              *string `protobuf:"bytes,5,opt,name=uid" json:"uid,omitempty"`
	TypeId           *int32  `protobuf:"varint,6,opt,name=typeId" json:"typeId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserRoleInfo) Reset()                    { *m = UserRoleInfo{} }
func (m *UserRoleInfo) String() string            { return proto.CompactTextString(m) }
func (*UserRoleInfo) ProtoMessage()               {}
func (*UserRoleInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserRoleInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *UserRoleInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserRoleInfo) GetServer() int32 {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return 0
}

func (m *UserRoleInfo) GetCtime() int64 {
	if m != nil && m.Ctime != nil {
		return *m.Ctime
	}
	return 0
}

func (m *UserRoleInfo) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *UserRoleInfo) GetTypeId() int32 {
	if m != nil && m.TypeId != nil {
		return *m.TypeId
	}
	return 0
}

type LogicServerInfo struct {
	Id               *int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	State            *string `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	Start            *int64  `protobuf:"varint,4,opt,name=start" json:"start,omitempty"`
	End              *int64  `protobuf:"varint,5,opt,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LogicServerInfo) Reset()                    { *m = LogicServerInfo{} }
func (m *LogicServerInfo) String() string            { return proto.CompactTextString(m) }
func (*LogicServerInfo) ProtoMessage()               {}
func (*LogicServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogicServerInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *LogicServerInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *LogicServerInfo) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *LogicServerInfo) GetStart() int64 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *LogicServerInfo) GetEnd() int64 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "UserInfo")
	proto.RegisterType((*UserRoleInfo)(nil), "UserRoleInfo")
	proto.RegisterType((*LogicServerInfo)(nil), "LogicServerInfo")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0x31, 0xaf, 0x82, 0x30,
	0x14, 0x85, 0x03, 0xa5, 0xe4, 0xbd, 0xfb, 0xe0, 0x99, 0x74, 0xea, 0x48, 0x98, 0x98, 0x9c, 0xfc,
	0x13, 0x24, 0x4e, 0x1a, 0xdd, 0x1b, 0x7a, 0xd5, 0x26, 0x42, 0x49, 0x7b, 0xd1, 0xf8, 0xef, 0x4d,
	0x8b, 0xe8, 0xe8, 0xd6, 0x93, 0x9e, 0xef, 0x7c, 0x17, 0x40, 0x4d, 0x74, 0x59, 0x8f, 0xce, 0x92,
	0xad, 0x37, 0xf0, 0x73, 0xf0, 0xe8, 0xda, 0xe1, 0x64, 0x45, 0x01, 0xd9, 0xa0, 0x7a, 0x94, 0x49,
	0x95, 0x34, 0xbf, 0xe2, 0x1f, 0xf2, 0x51, 0x79, 0x7f, 0xd7, 0x32, 0x8d, 0x19, 0x20, 0x35, 0x5a,
	0xb2, 0xf0, 0xae, 0x35, 0x14, 0x81, 0xda, 0xd9, 0x2b, 0x46, 0x72, 0xfe, 0x0b, 0x1c, 0x7f, 0xaf,
	0xa4, 0xcb, 0x8a, 0x47, 0x77, 0x43, 0x17, 0x49, 0x2e, 0x4a, 0xe0, 0x1d, 0x99, 0x1e, 0x65, 0x56,
	0x25, 0x0d, 0x13, 0x7f, 0xc0, 0x26, 0xa3, 0x25, 0x5f, 0xba, 0xf4, 0x18, 0xb1, 0xd5, 0x32, 0x0f,
	0xdd, 0xfa, 0x08, 0xab, 0xad, 0x3d, 0x9b, 0x6e, 0x1f, 0x07, 0xbe, 0x88, 0x4a, 0xe0, 0x9e, 0x14,
	0xe1, 0x7c, 0xe1, 0x2b, 0x3a, 0xfa, 0x78, 0x70, 0x98, 0x3d, 0xec, 0x19, 0x00, 0x00, 0xff, 0xff,
	0x0b, 0xc3, 0x72, 0x9c, 0x00, 0x01, 0x00, 0x00,
}
