// Code generated by protoc-gen-go.
// source: friend.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 好友
type Friend struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Friend) Reset()                    { *m = Friend{} }
func (m *Friend) String() string            { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()               {}
func (*Friend) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Friend) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// 玩家发起好友请求
type GamerAddFriendC2S struct {
	Request          *FriendRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GamerAddFriendC2S) Reset()                    { *m = GamerAddFriendC2S{} }
func (m *GamerAddFriendC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerAddFriendC2S) ProtoMessage()               {}
func (*GamerAddFriendC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *GamerAddFriendC2S) GetRequest() *FriendRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

// 玩家获取好友请求
type GamerGetFriendRequestC2S struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerGetFriendRequestC2S) Reset()                    { *m = GamerGetFriendRequestC2S{} }
func (m *GamerGetFriendRequestC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerGetFriendRequestC2S) ProtoMessage()               {}
func (*GamerGetFriendRequestC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *GamerGetFriendRequestC2S) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// 玩家获取好友请求
type GamerGetFriendRequestS2C struct {
	Requests         []*FriendRequest `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GamerGetFriendRequestS2C) Reset()                    { *m = GamerGetFriendRequestS2C{} }
func (m *GamerGetFriendRequestS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerGetFriendRequestS2C) ProtoMessage()               {}
func (*GamerGetFriendRequestS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *GamerGetFriendRequestS2C) GetRequests() []*FriendRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

// 玩家处理好友请求
type GamerDealFriendRequestC2S struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Oid              *int32 `protobuf:"varint,2,opt,name=oid" json:"oid,omitempty"`
	Result           *int32 `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDealFriendRequestC2S) Reset()                    { *m = GamerDealFriendRequestC2S{} }
func (m *GamerDealFriendRequestC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerDealFriendRequestC2S) ProtoMessage()               {}
func (*GamerDealFriendRequestC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *GamerDealFriendRequestC2S) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GamerDealFriendRequestC2S) GetOid() int32 {
	if m != nil && m.Oid != nil {
		return *m.Oid
	}
	return 0
}

func (m *GamerDealFriendRequestC2S) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 玩家处理好友请求
type GamerDealFriendRequestS2C struct {
	Friend           *Gamer `protobuf:"bytes,1,opt,name=friend" json:"friend,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDealFriendRequestS2C) Reset()                    { *m = GamerDealFriendRequestS2C{} }
func (m *GamerDealFriendRequestS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerDealFriendRequestS2C) ProtoMessage()               {}
func (*GamerDealFriendRequestS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *GamerDealFriendRequestS2C) GetFriend() *Gamer {
	if m != nil {
		return m.Friend
	}
	return nil
}

// 清空好友请求
type GamerClearFriendRequestC2S struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerClearFriendRequestC2S) Reset()                    { *m = GamerClearFriendRequestC2S{} }
func (m *GamerClearFriendRequestC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerClearFriendRequestC2S) ProtoMessage()               {}
func (*GamerClearFriendRequestC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *GamerClearFriendRequestC2S) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// 玩家获取好友
type GamerGetAllFriendC2S struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerGetAllFriendC2S) Reset()                    { *m = GamerGetAllFriendC2S{} }
func (m *GamerGetAllFriendC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerGetAllFriendC2S) ProtoMessage()               {}
func (*GamerGetAllFriendC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *GamerGetAllFriendC2S) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// 玩家获取好友
type GamerGetAllFriendS2C struct {
	Friends          []*Gamer `protobuf:"bytes,1,rep,name=friends" json:"friends,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GamerGetAllFriendS2C) Reset()                    { *m = GamerGetAllFriendS2C{} }
func (m *GamerGetAllFriendS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerGetAllFriendS2C) ProtoMessage()               {}
func (*GamerGetAllFriendS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *GamerGetAllFriendS2C) GetFriends() []*Gamer {
	if m != nil {
		return m.Friends
	}
	return nil
}

// 删除好友
type GamerDelFriendC2S struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Oid              *int32 `protobuf:"varint,2,opt,name=oid" json:"oid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDelFriendC2S) Reset()                    { *m = GamerDelFriendC2S{} }
func (m *GamerDelFriendC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerDelFriendC2S) ProtoMessage()               {}
func (*GamerDelFriendC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *GamerDelFriendC2S) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GamerDelFriendC2S) GetOid() int32 {
	if m != nil && m.Oid != nil {
		return *m.Oid
	}
	return 0
}

// 删除好友
type GamerDelFriendS2C struct {
	Friends          []*Gamer `protobuf:"bytes,1,rep,name=friends" json:"friends,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GamerDelFriendS2C) Reset()                    { *m = GamerDelFriendS2C{} }
func (m *GamerDelFriendS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerDelFriendS2C) ProtoMessage()               {}
func (*GamerDelFriendS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *GamerDelFriendS2C) GetFriends() []*Gamer {
	if m != nil {
		return m.Friends
	}
	return nil
}

// 已拥有球员
type GamerOwnerPlayerC2S struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerOwnerPlayerC2S) Reset()                    { *m = GamerOwnerPlayerC2S{} }
func (m *GamerOwnerPlayerC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerOwnerPlayerC2S) ProtoMessage()               {}
func (*GamerOwnerPlayerC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

func (m *GamerOwnerPlayerC2S) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// 已拥有球员列表
type GamerOwnerPlayerS2C struct {
	Players          []*Player `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GamerOwnerPlayerS2C) Reset()                    { *m = GamerOwnerPlayerS2C{} }
func (m *GamerOwnerPlayerS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerOwnerPlayerS2C) ProtoMessage()               {}
func (*GamerOwnerPlayerS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{12} }

func (m *GamerOwnerPlayerS2C) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

// 购买球员
type GamerBuyPlayerC2S struct {
	GamerId          *int32 `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	PlayerId         *int32 `protobuf:"varint,2,opt,name=playerId" json:"playerId,omitempty"`
	CoinType         *int32 `protobuf:"varint,3,opt,name=coinType" json:"coinType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerBuyPlayerC2S) Reset()                    { *m = GamerBuyPlayerC2S{} }
func (m *GamerBuyPlayerC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerBuyPlayerC2S) ProtoMessage()               {}
func (*GamerBuyPlayerC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{13} }

func (m *GamerBuyPlayerC2S) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

func (m *GamerBuyPlayerC2S) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *GamerBuyPlayerC2S) GetCoinType() int32 {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return 0
}

// 购买球员
type GamerBuyPlayerS2C struct {
	Player           *Player `protobuf:"bytes,1,opt,name=player" json:"player,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamerBuyPlayerS2C) Reset()                    { *m = GamerBuyPlayerS2C{} }
func (m *GamerBuyPlayerS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerBuyPlayerS2C) ProtoMessage()               {}
func (*GamerBuyPlayerS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{14} }

func (m *GamerBuyPlayerS2C) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

// 获取背包数据
type GamerGetPackC2S struct {
	Gid              *int32 `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerGetPackC2S) Reset()                    { *m = GamerGetPackC2S{} }
func (m *GamerGetPackC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerGetPackC2S) ProtoMessage()               {}
func (*GamerGetPackC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{15} }

func (m *GamerGetPackC2S) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

type GamerGetPackS2C struct {
	Goods            []*ItemConfig `protobuf:"bytes,1,rep,name=goods" json:"goods,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GamerGetPackS2C) Reset()                    { *m = GamerGetPackS2C{} }
func (m *GamerGetPackS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerGetPackS2C) ProtoMessage()               {}
func (*GamerGetPackS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{16} }

func (m *GamerGetPackS2C) GetGoods() []*ItemConfig {
	if m != nil {
		return m.Goods
	}
	return nil
}

// 玩家使用物品
type GamerUseGoodsC2S struct {
	Gid              *int32 `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Id               *int32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Count            *int32 `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerUseGoodsC2S) Reset()                    { *m = GamerUseGoodsC2S{} }
func (m *GamerUseGoodsC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerUseGoodsC2S) ProtoMessage()               {}
func (*GamerUseGoodsC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{17} }

func (m *GamerUseGoodsC2S) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *GamerUseGoodsC2S) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GamerUseGoodsC2S) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

// 玩家使用物品
type GamerUseGoodsS2C struct {
	Goods            *ItemConfig `protobuf:"bytes,1,opt,name=goods" json:"goods,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GamerUseGoodsS2C) Reset()                    { *m = GamerUseGoodsS2C{} }
func (m *GamerUseGoodsS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerUseGoodsS2C) ProtoMessage()               {}
func (*GamerUseGoodsS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{18} }

func (m *GamerUseGoodsS2C) GetGoods() *ItemConfig {
	if m != nil {
		return m.Goods
	}
	return nil
}

// 玩家出售物品
type GamerSellGoodsC2S struct {
	Gid              *int32 `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Id               *int32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Count            *int32 `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerSellGoodsC2S) Reset()                    { *m = GamerSellGoodsC2S{} }
func (m *GamerSellGoodsC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerSellGoodsC2S) ProtoMessage()               {}
func (*GamerSellGoodsC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{19} }

func (m *GamerSellGoodsC2S) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *GamerSellGoodsC2S) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GamerSellGoodsC2S) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

// 玩家出售物品
type GamerSellGoodsS2C struct {
	SellGoods        *ItemConfig `protobuf:"bytes,1,opt,name=sellGoods" json:"sellGoods,omitempty"`
	GetGoods         *ItemConfig `protobuf:"bytes,2,opt,name=getGoods" json:"getGoods,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GamerSellGoodsS2C) Reset()                    { *m = GamerSellGoodsS2C{} }
func (m *GamerSellGoodsS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerSellGoodsS2C) ProtoMessage()               {}
func (*GamerSellGoodsS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{20} }

func (m *GamerSellGoodsS2C) GetSellGoods() *ItemConfig {
	if m != nil {
		return m.SellGoods
	}
	return nil
}

func (m *GamerSellGoodsS2C) GetGetGoods() *ItemConfig {
	if m != nil {
		return m.GetGoods
	}
	return nil
}

// 快速重连
type FastReconnC2S struct {
	Gid              *int32  `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Session          *string `protobuf:"bytes,2,opt,name=session" json:"session,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FastReconnC2S) Reset()                    { *m = FastReconnC2S{} }
func (m *FastReconnC2S) String() string            { return proto.CompactTextString(m) }
func (*FastReconnC2S) ProtoMessage()               {}
func (*FastReconnC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{21} }

func (m *FastReconnC2S) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *FastReconnC2S) GetSession() string {
	if m != nil && m.Session != nil {
		return *m.Session
	}
	return ""
}

// 球员招募
type GamerEmployPlayerC2S struct {
	GamerId          *int32 `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	SelectId         *int32 `protobuf:"varint,2,opt,name=selectId" json:"selectId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerEmployPlayerC2S) Reset()                    { *m = GamerEmployPlayerC2S{} }
func (m *GamerEmployPlayerC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerEmployPlayerC2S) ProtoMessage()               {}
func (*GamerEmployPlayerC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{22} }

func (m *GamerEmployPlayerC2S) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

func (m *GamerEmployPlayerC2S) GetSelectId() int32 {
	if m != nil && m.SelectId != nil {
		return *m.SelectId
	}
	return 0
}

// 球员招募
type GamerEmployPlayerS2C struct {
	Gift             []*ItemConfig `protobuf:"bytes,1,rep,name=gift" json:"gift,omitempty"`
	Cast             []*ItemConfig `protobuf:"bytes,2,rep,name=cast" json:"cast,omitempty"`
	RecruitTime      *int64        `protobuf:"varint,3,opt,name=recruitTime" json:"recruitTime,omitempty"`
	FreeCnt          *int32        `protobuf:"varint,4,opt,name=freeCnt" json:"freeCnt,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GamerEmployPlayerS2C) Reset()                    { *m = GamerEmployPlayerS2C{} }
func (m *GamerEmployPlayerS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerEmployPlayerS2C) ProtoMessage()               {}
func (*GamerEmployPlayerS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{23} }

func (m *GamerEmployPlayerS2C) GetGift() []*ItemConfig {
	if m != nil {
		return m.Gift
	}
	return nil
}

func (m *GamerEmployPlayerS2C) GetCast() []*ItemConfig {
	if m != nil {
		return m.Cast
	}
	return nil
}

func (m *GamerEmployPlayerS2C) GetRecruitTime() int64 {
	if m != nil && m.RecruitTime != nil {
		return *m.RecruitTime
	}
	return 0
}

func (m *GamerEmployPlayerS2C) GetFreeCnt() int32 {
	if m != nil && m.FreeCnt != nil {
		return *m.FreeCnt
	}
	return 0
}

// 球员升级
type GamerPlayerLvC2S struct {
	GamerId          *int32 `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	PlayerId         *int32 `protobuf:"varint,2,opt,name=playerId" json:"playerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerPlayerLvC2S) Reset()                    { *m = GamerPlayerLvC2S{} }
func (m *GamerPlayerLvC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerPlayerLvC2S) ProtoMessage()               {}
func (*GamerPlayerLvC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{24} }

func (m *GamerPlayerLvC2S) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

func (m *GamerPlayerLvC2S) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

// 球员升级
type GamerPlayerLvS2C struct {
	PlayerId         *int32        `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
	IsCrit           *bool         `protobuf:"varint,2,opt,name=isCrit" json:"isCrit,omitempty"`
	PlayerLv         *int32        `protobuf:"varint,3,opt,name=playerLv" json:"playerLv,omitempty"`
	PlayerExp        []*ItemConfig `protobuf:"bytes,4,rep,name=playerExp" json:"playerExp,omitempty"`
	Cast             []*ItemConfig `protobuf:"bytes,5,rep,name=cast" json:"cast,omitempty"`
	Res              []*ItemConfig `protobuf:"bytes,6,rep,name=res" json:"res,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GamerPlayerLvS2C) Reset()                    { *m = GamerPlayerLvS2C{} }
func (m *GamerPlayerLvS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerPlayerLvS2C) ProtoMessage()               {}
func (*GamerPlayerLvS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{25} }

func (m *GamerPlayerLvS2C) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *GamerPlayerLvS2C) GetIsCrit() bool {
	if m != nil && m.IsCrit != nil {
		return *m.IsCrit
	}
	return false
}

func (m *GamerPlayerLvS2C) GetPlayerLv() int32 {
	if m != nil && m.PlayerLv != nil {
		return *m.PlayerLv
	}
	return 0
}

func (m *GamerPlayerLvS2C) GetPlayerExp() []*ItemConfig {
	if m != nil {
		return m.PlayerExp
	}
	return nil
}

func (m *GamerPlayerLvS2C) GetCast() []*ItemConfig {
	if m != nil {
		return m.Cast
	}
	return nil
}

func (m *GamerPlayerLvS2C) GetRes() []*ItemConfig {
	if m != nil {
		return m.Res
	}
	return nil
}

// 球员突破
type GamerPlayerBreadthroughC2S struct {
	GamerId          *int32 `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	PlayerId         *int32 `protobuf:"varint,2,opt,name=playerId" json:"playerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerPlayerBreadthroughC2S) Reset()                    { *m = GamerPlayerBreadthroughC2S{} }
func (m *GamerPlayerBreadthroughC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerPlayerBreadthroughC2S) ProtoMessage()               {}
func (*GamerPlayerBreadthroughC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{26} }

func (m *GamerPlayerBreadthroughC2S) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

func (m *GamerPlayerBreadthroughC2S) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

// 球员突破
type GamerPlayerBreadthroughS2C struct {
	PlayerId         *int32        `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
	PlayerLv         *int32        `protobuf:"varint,2,opt,name=playerLv" json:"playerLv,omitempty"`
	PlayerExp        []*ItemConfig `protobuf:"bytes,3,rep,name=playerExp" json:"playerExp,omitempty"`
	Cast             []*ItemConfig `protobuf:"bytes,4,rep,name=cast" json:"cast,omitempty"`
	Res              []*ItemConfig `protobuf:"bytes,5,rep,name=res" json:"res,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GamerPlayerBreadthroughS2C) Reset()                    { *m = GamerPlayerBreadthroughS2C{} }
func (m *GamerPlayerBreadthroughS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerPlayerBreadthroughS2C) ProtoMessage()               {}
func (*GamerPlayerBreadthroughS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{27} }

func (m *GamerPlayerBreadthroughS2C) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *GamerPlayerBreadthroughS2C) GetPlayerLv() int32 {
	if m != nil && m.PlayerLv != nil {
		return *m.PlayerLv
	}
	return 0
}

func (m *GamerPlayerBreadthroughS2C) GetPlayerExp() []*ItemConfig {
	if m != nil {
		return m.PlayerExp
	}
	return nil
}

func (m *GamerPlayerBreadthroughS2C) GetCast() []*ItemConfig {
	if m != nil {
		return m.Cast
	}
	return nil
}

func (m *GamerPlayerBreadthroughS2C) GetRes() []*ItemConfig {
	if m != nil {
		return m.Res
	}
	return nil
}

// 玩家获取邮件
type GamerGetMailC2S struct {
	Gid              *int32 `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerGetMailC2S) Reset()                    { *m = GamerGetMailC2S{} }
func (m *GamerGetMailC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerGetMailC2S) ProtoMessage()               {}
func (*GamerGetMailC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{28} }

func (m *GamerGetMailC2S) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

// 玩家获取邮件
type GamerGetMailS2C struct {
	Mails            []*Mail `protobuf:"bytes,1,rep,name=mails" json:"mails,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamerGetMailS2C) Reset()                    { *m = GamerGetMailS2C{} }
func (m *GamerGetMailS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerGetMailS2C) ProtoMessage()               {}
func (*GamerGetMailS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{29} }

func (m *GamerGetMailS2C) GetMails() []*Mail {
	if m != nil {
		return m.Mails
	}
	return nil
}

// 玩家删除邮件
type GamerDelMailC2S struct {
	Gid              *int32 `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Mid              *int64 `protobuf:"varint,2,opt,name=mid" json:"mid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDelMailC2S) Reset()                    { *m = GamerDelMailC2S{} }
func (m *GamerDelMailC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerDelMailC2S) ProtoMessage()               {}
func (*GamerDelMailC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{30} }

func (m *GamerDelMailC2S) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *GamerDelMailC2S) GetMid() int64 {
	if m != nil && m.Mid != nil {
		return *m.Mid
	}
	return 0
}

// 玩家删除邮件
type GamerDelMailS2C struct {
	Mid              *int64 `protobuf:"varint,1,opt,name=mid" json:"mid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDelMailS2C) Reset()                    { *m = GamerDelMailS2C{} }
func (m *GamerDelMailS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerDelMailS2C) ProtoMessage()               {}
func (*GamerDelMailS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{31} }

func (m *GamerDelMailS2C) GetMid() int64 {
	if m != nil && m.Mid != nil {
		return *m.Mid
	}
	return 0
}

// 玩家收取附件
type GamerReceiveAttachmentC2S struct {
	Gid              *int32 `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Mid              *int64 `protobuf:"varint,2,opt,name=mid" json:"mid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerReceiveAttachmentC2S) Reset()                    { *m = GamerReceiveAttachmentC2S{} }
func (m *GamerReceiveAttachmentC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerReceiveAttachmentC2S) ProtoMessage()               {}
func (*GamerReceiveAttachmentC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{32} }

func (m *GamerReceiveAttachmentC2S) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *GamerReceiveAttachmentC2S) GetMid() int64 {
	if m != nil && m.Mid != nil {
		return *m.Mid
	}
	return 0
}

// 玩家收取附件
type GamerReceiveAttachmentS2C struct {
	Attachments      []*ItemConfig `protobuf:"bytes,1,rep,name=attachments" json:"attachments,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GamerReceiveAttachmentS2C) Reset()                    { *m = GamerReceiveAttachmentS2C{} }
func (m *GamerReceiveAttachmentS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerReceiveAttachmentS2C) ProtoMessage()               {}
func (*GamerReceiveAttachmentS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{33} }

func (m *GamerReceiveAttachmentS2C) GetAttachments() []*ItemConfig {
	if m != nil {
		return m.Attachments
	}
	return nil
}

// 玩家阅读邮件
type GamerReadMailC2S struct {
	Gid              *int32 `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Mid              *int64 `protobuf:"varint,2,opt,name=mid" json:"mid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerReadMailC2S) Reset()                    { *m = GamerReadMailC2S{} }
func (m *GamerReadMailC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerReadMailC2S) ProtoMessage()               {}
func (*GamerReadMailC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{34} }

func (m *GamerReadMailC2S) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *GamerReadMailC2S) GetMid() int64 {
	if m != nil && m.Mid != nil {
		return *m.Mid
	}
	return 0
}

// 设置玩家签名
type GamerSetSignC2S struct {
	Gid              *int32  `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Sign             *string `protobuf:"bytes,2,opt,name=sign" json:"sign,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamerSetSignC2S) Reset()                    { *m = GamerSetSignC2S{} }
func (m *GamerSetSignC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerSetSignC2S) ProtoMessage()               {}
func (*GamerSetSignC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{35} }

func (m *GamerSetSignC2S) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *GamerSetSignC2S) GetSign() string {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return ""
}

// 设置玩家头像
type GamerSetIconC2S struct {
	Gid              *int32 `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Icon             *int32 `protobuf:"varint,2,opt,name=icon" json:"icon,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerSetIconC2S) Reset()                    { *m = GamerSetIconC2S{} }
func (m *GamerSetIconC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerSetIconC2S) ProtoMessage()               {}
func (*GamerSetIconC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{36} }

func (m *GamerSetIconC2S) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *GamerSetIconC2S) GetIcon() int32 {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return 0
}

// 设置玩家名字
type GamerSetNameC2S struct {
	Gid              *int32  `protobuf:"varint,1,opt,name=gid" json:"gid,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamerSetNameC2S) Reset()                    { *m = GamerSetNameC2S{} }
func (m *GamerSetNameC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerSetNameC2S) ProtoMessage()               {}
func (*GamerSetNameC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{37} }

func (m *GamerSetNameC2S) GetGid() int32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *GamerSetNameC2S) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

// 玩家解锁球员特质槽
type GamerGetPlayerSpecialityC2S struct {
	GamerId          *int32 `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	PlayerId         *int32 `protobuf:"varint,2,opt,name=playerId" json:"playerId,omitempty"`
	SlotId           *int32 `protobuf:"varint,3,opt,name=slotId" json:"slotId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerGetPlayerSpecialityC2S) Reset()                    { *m = GamerGetPlayerSpecialityC2S{} }
func (m *GamerGetPlayerSpecialityC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerGetPlayerSpecialityC2S) ProtoMessage()               {}
func (*GamerGetPlayerSpecialityC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{38} }

func (m *GamerGetPlayerSpecialityC2S) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

func (m *GamerGetPlayerSpecialityC2S) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *GamerGetPlayerSpecialityC2S) GetSlotId() int32 {
	if m != nil && m.SlotId != nil {
		return *m.SlotId
	}
	return 0
}

// 玩家解锁球员特质槽
type GamerGetPlayerSpecialityS2C struct {
	PlayerId         *int32              `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
	Speciality       []*PlayerSpeciality `protobuf:"bytes,2,rep,name=speciality" json:"speciality,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GamerGetPlayerSpecialityS2C) Reset()                    { *m = GamerGetPlayerSpecialityS2C{} }
func (m *GamerGetPlayerSpecialityS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerGetPlayerSpecialityS2C) ProtoMessage()               {}
func (*GamerGetPlayerSpecialityS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{39} }

func (m *GamerGetPlayerSpecialityS2C) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *GamerGetPlayerSpecialityS2C) GetSpeciality() []*PlayerSpeciality {
	if m != nil {
		return m.Speciality
	}
	return nil
}

// 玩家刷新球员特质
type GamerUpdatePlayerSpecialityC2S struct {
	GamerId          *int32 `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	PlayerId         *int32 `protobuf:"varint,2,opt,name=playerId" json:"playerId,omitempty"`
	SlotId           *int32 `protobuf:"varint,3,opt,name=slotId" json:"slotId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerUpdatePlayerSpecialityC2S) Reset()                    { *m = GamerUpdatePlayerSpecialityC2S{} }
func (m *GamerUpdatePlayerSpecialityC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerUpdatePlayerSpecialityC2S) ProtoMessage()               {}
func (*GamerUpdatePlayerSpecialityC2S) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{40} }

func (m *GamerUpdatePlayerSpecialityC2S) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

func (m *GamerUpdatePlayerSpecialityC2S) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *GamerUpdatePlayerSpecialityC2S) GetSlotId() int32 {
	if m != nil && m.SlotId != nil {
		return *m.SlotId
	}
	return 0
}

// 玩家刷新球员特质
type GamerUpdatePlayerSpecialityS2C struct {
	PlayerId         *int32              `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
	Speciality       []*PlayerSpeciality `protobuf:"bytes,2,rep,name=speciality" json:"speciality,omitempty"`
	GoodsUpdate      []*ItemConfig       `protobuf:"bytes,3,rep,name=goodsUpdate" json:"goodsUpdate,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GamerUpdatePlayerSpecialityS2C) Reset()                    { *m = GamerUpdatePlayerSpecialityS2C{} }
func (m *GamerUpdatePlayerSpecialityS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerUpdatePlayerSpecialityS2C) ProtoMessage()               {}
func (*GamerUpdatePlayerSpecialityS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{41} }

func (m *GamerUpdatePlayerSpecialityS2C) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *GamerUpdatePlayerSpecialityS2C) GetSpeciality() []*PlayerSpeciality {
	if m != nil {
		return m.Speciality
	}
	return nil
}

func (m *GamerUpdatePlayerSpecialityS2C) GetGoodsUpdate() []*ItemConfig {
	if m != nil {
		return m.GoodsUpdate
	}
	return nil
}

// 玩家日常签到
type GamerDailySignInC2C struct {
	GamerId          *int32 `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerDailySignInC2C) Reset()                    { *m = GamerDailySignInC2C{} }
func (m *GamerDailySignInC2C) String() string            { return proto.CompactTextString(m) }
func (*GamerDailySignInC2C) ProtoMessage()               {}
func (*GamerDailySignInC2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{42} }

func (m *GamerDailySignInC2C) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

// 玩家日常签到
type GamerDailySignInS2C struct {
	GamerId          *int32        `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	SignInGoods      []*ItemConfig `protobuf:"bytes,2,rep,name=signInGoods" json:"signInGoods,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GamerDailySignInS2C) Reset()                    { *m = GamerDailySignInS2C{} }
func (m *GamerDailySignInS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerDailySignInS2C) ProtoMessage()               {}
func (*GamerDailySignInS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{43} }

func (m *GamerDailySignInS2C) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

func (m *GamerDailySignInS2C) GetSignInGoods() []*ItemConfig {
	if m != nil {
		return m.SignInGoods
	}
	return nil
}

// 玩家补签到
type GamerRemedySignInC2C struct {
	GamerId          *int32  `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	Data             *string `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamerRemedySignInC2C) Reset()                    { *m = GamerRemedySignInC2C{} }
func (m *GamerRemedySignInC2C) String() string            { return proto.CompactTextString(m) }
func (*GamerRemedySignInC2C) ProtoMessage()               {}
func (*GamerRemedySignInC2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{44} }

func (m *GamerRemedySignInC2C) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

func (m *GamerRemedySignInC2C) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

// 玩家补签到
type GamerRemedySignInS2C struct {
	GamerId          *int32        `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	SignInGoods      []*ItemConfig `protobuf:"bytes,2,rep,name=signInGoods" json:"signInGoods,omitempty"`
	GoodsUpdate      []*ItemConfig `protobuf:"bytes,3,rep,name=goodsUpdate" json:"goodsUpdate,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GamerRemedySignInS2C) Reset()                    { *m = GamerRemedySignInS2C{} }
func (m *GamerRemedySignInS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerRemedySignInS2C) ProtoMessage()               {}
func (*GamerRemedySignInS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{45} }

func (m *GamerRemedySignInS2C) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

func (m *GamerRemedySignInS2C) GetSignInGoods() []*ItemConfig {
	if m != nil {
		return m.SignInGoods
	}
	return nil
}

func (m *GamerRemedySignInS2C) GetGoodsUpdate() []*ItemConfig {
	if m != nil {
		return m.GoodsUpdate
	}
	return nil
}

// 玩家累计签到
type GamerTotalSignInC2C struct {
	GamerId          *int32 `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	GrandTotal       *int32 `protobuf:"varint,2,opt,name=grandTotal" json:"grandTotal,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GamerTotalSignInC2C) Reset()                    { *m = GamerTotalSignInC2C{} }
func (m *GamerTotalSignInC2C) String() string            { return proto.CompactTextString(m) }
func (*GamerTotalSignInC2C) ProtoMessage()               {}
func (*GamerTotalSignInC2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{46} }

func (m *GamerTotalSignInC2C) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

func (m *GamerTotalSignInC2C) GetGrandTotal() int32 {
	if m != nil && m.GrandTotal != nil {
		return *m.GrandTotal
	}
	return 0
}

// 玩家累计签到
type GamerTotalSignInS2C struct {
	GamerId          *int32        `protobuf:"varint,1,opt,name=gamerId" json:"gamerId,omitempty"`
	SignInGoods      []*ItemConfig `protobuf:"bytes,2,rep,name=signInGoods" json:"signInGoods,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GamerTotalSignInS2C) Reset()                    { *m = GamerTotalSignInS2C{} }
func (m *GamerTotalSignInS2C) String() string            { return proto.CompactTextString(m) }
func (*GamerTotalSignInS2C) ProtoMessage()               {}
func (*GamerTotalSignInS2C) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{47} }

func (m *GamerTotalSignInS2C) GetGamerId() int32 {
	if m != nil && m.GamerId != nil {
		return *m.GamerId
	}
	return 0
}

func (m *GamerTotalSignInS2C) GetSignInGoods() []*ItemConfig {
	if m != nil {
		return m.SignInGoods
	}
	return nil
}

func init() {
	proto.RegisterType((*Friend)(nil), "Friend")
	proto.RegisterType((*GamerAddFriendC2S)(nil), "GamerAddFriendC2S")
	proto.RegisterType((*GamerGetFriendRequestC2S)(nil), "GamerGetFriendRequestC2S")
	proto.RegisterType((*GamerGetFriendRequestS2C)(nil), "GamerGetFriendRequestS2C")
	proto.RegisterType((*GamerDealFriendRequestC2S)(nil), "GamerDealFriendRequestC2S")
	proto.RegisterType((*GamerDealFriendRequestS2C)(nil), "GamerDealFriendRequestS2C")
	proto.RegisterType((*GamerClearFriendRequestC2S)(nil), "GamerClearFriendRequestC2S")
	proto.RegisterType((*GamerGetAllFriendC2S)(nil), "GamerGetAllFriendC2S")
	proto.RegisterType((*GamerGetAllFriendS2C)(nil), "GamerGetAllFriendS2C")
	proto.RegisterType((*GamerDelFriendC2S)(nil), "GamerDelFriendC2S")
	proto.RegisterType((*GamerDelFriendS2C)(nil), "GamerDelFriendS2C")
	proto.RegisterType((*GamerOwnerPlayerC2S)(nil), "GamerOwnerPlayerC2S")
	proto.RegisterType((*GamerOwnerPlayerS2C)(nil), "GamerOwnerPlayerS2C")
	proto.RegisterType((*GamerBuyPlayerC2S)(nil), "GamerBuyPlayerC2S")
	proto.RegisterType((*GamerBuyPlayerS2C)(nil), "GamerBuyPlayerS2C")
	proto.RegisterType((*GamerGetPackC2S)(nil), "GamerGetPackC2S")
	proto.RegisterType((*GamerGetPackS2C)(nil), "GamerGetPackS2C")
	proto.RegisterType((*GamerUseGoodsC2S)(nil), "GamerUseGoodsC2S")
	proto.RegisterType((*GamerUseGoodsS2C)(nil), "GamerUseGoodsS2C")
	proto.RegisterType((*GamerSellGoodsC2S)(nil), "GamerSellGoodsC2S")
	proto.RegisterType((*GamerSellGoodsS2C)(nil), "GamerSellGoodsS2C")
	proto.RegisterType((*FastReconnC2S)(nil), "FastReconnC2S")
	proto.RegisterType((*GamerEmployPlayerC2S)(nil), "GamerEmployPlayerC2S")
	proto.RegisterType((*GamerEmployPlayerS2C)(nil), "GamerEmployPlayerS2C")
	proto.RegisterType((*GamerPlayerLvC2S)(nil), "GamerPlayerLvC2S")
	proto.RegisterType((*GamerPlayerLvS2C)(nil), "GamerPlayerLvS2C")
	proto.RegisterType((*GamerPlayerBreadthroughC2S)(nil), "GamerPlayerBreadthroughC2S")
	proto.RegisterType((*GamerPlayerBreadthroughS2C)(nil), "GamerPlayerBreadthroughS2C")
	proto.RegisterType((*GamerGetMailC2S)(nil), "GamerGetMailC2S")
	proto.RegisterType((*GamerGetMailS2C)(nil), "GamerGetMailS2C")
	proto.RegisterType((*GamerDelMailC2S)(nil), "GamerDelMailC2S")
	proto.RegisterType((*GamerDelMailS2C)(nil), "GamerDelMailS2C")
	proto.RegisterType((*GamerReceiveAttachmentC2S)(nil), "GamerReceiveAttachmentC2S")
	proto.RegisterType((*GamerReceiveAttachmentS2C)(nil), "GamerReceiveAttachmentS2C")
	proto.RegisterType((*GamerReadMailC2S)(nil), "GamerReadMailC2S")
	proto.RegisterType((*GamerSetSignC2S)(nil), "GamerSetSignC2S")
	proto.RegisterType((*GamerSetIconC2S)(nil), "GamerSetIconC2S")
	proto.RegisterType((*GamerSetNameC2S)(nil), "GamerSetNameC2S")
	proto.RegisterType((*GamerGetPlayerSpecialityC2S)(nil), "GamerGetPlayerSpecialityC2S")
	proto.RegisterType((*GamerGetPlayerSpecialityS2C)(nil), "GamerGetPlayerSpecialityS2C")
	proto.RegisterType((*GamerUpdatePlayerSpecialityC2S)(nil), "GamerUpdatePlayerSpecialityC2S")
	proto.RegisterType((*GamerUpdatePlayerSpecialityS2C)(nil), "GamerUpdatePlayerSpecialityS2C")
	proto.RegisterType((*GamerDailySignInC2C)(nil), "GamerDailySignInC2C")
	proto.RegisterType((*GamerDailySignInS2C)(nil), "GamerDailySignInS2C")
	proto.RegisterType((*GamerRemedySignInC2C)(nil), "GamerRemedySignInC2C")
	proto.RegisterType((*GamerRemedySignInS2C)(nil), "GamerRemedySignInS2C")
	proto.RegisterType((*GamerTotalSignInC2C)(nil), "GamerTotalSignInC2C")
	proto.RegisterType((*GamerTotalSignInS2C)(nil), "GamerTotalSignInS2C")
}

func init() { proto.RegisterFile("friend.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 892 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x6f, 0x1b, 0x45,
	0x14, 0x95, 0xbf, 0xdd, 0xeb, 0x34, 0x49, 0xdd, 0x08, 0xb6, 0x41, 0x84, 0xb0, 0x12, 0xa5, 0x12,
	0xa9, 0x91, 0x02, 0x79, 0xa0, 0x80, 0x50, 0x6a, 0xb7, 0x89, 0xa5, 0x02, 0x91, 0x1d, 0x78, 0x1f,
	0xed, 0x5e, 0x6f, 0x46, 0x9d, 0xdd, 0x31, 0x33, 0xe3, 0x80, 0xc5, 0xef, 0xe0, 0x89, 0x3f, 0x8b,
	0xe6, 0x63, 0x1d, 0x67, 0x67, 0xd7, 0x35, 0x85, 0xb7, 0x9d, 0xbd, 0xe7, 0x9e, 0x73, 0xcf, 0xdc,
	0x3b, 0x33, 0xb0, 0x33, 0x13, 0x14, 0xb3, 0x78, 0x30, 0x17, 0x5c, 0xf1, 0xc3, 0x9d, 0x88, 0xa7,
	0x29, 0xcf, 0xdc, 0x0a, 0x22, 0x9e, 0xcd, 0xec, 0x77, 0x78, 0x00, 0xed, 0xd7, 0x06, 0xd9, 0x07,
	0xa8, 0xd3, 0x38, 0xa8, 0x1d, 0xd7, 0x9e, 0xb5, 0xc2, 0xaf, 0xe1, 0xd1, 0x05, 0x49, 0x51, 0x9c,
	0xc7, 0xb1, 0x8d, 0x0e, 0x4f, 0xa7, 0xfd, 0x4f, 0xa0, 0x23, 0xf0, 0xb7, 0x05, 0x4a, 0x65, 0x50,
	0xbd, 0xd3, 0xdd, 0x81, 0x0d, 0x4e, 0xec, 0xdf, 0xf0, 0x29, 0x04, 0x26, 0xeb, 0x02, 0xd5, 0xbd,
	0x80, 0x4e, 0x5e, 0x67, 0xff, 0xae, 0x02, 0x37, 0x3d, 0x1d, 0xf6, 0x8f, 0xa1, 0xeb, 0x44, 0x64,
	0x50, 0x3b, 0x6e, 0x94, 0xa8, 0x8c, 0xe0, 0x89, 0xc9, 0x1e, 0x21, 0x61, 0x9b, 0x64, 0xfa, 0x3d,
	0x68, 0x70, 0x1a, 0x07, 0x75, 0xb3, 0xd8, 0x85, 0xb6, 0x40, 0xb9, 0x60, 0x2a, 0x68, 0x98, 0x1a,
	0xbe, 0xaa, 0x62, 0xd1, 0x45, 0x7c, 0x00, 0x6d, 0xbb, 0x7d, 0xce, 0x68, 0x7b, 0x60, 0xb0, 0xe1,
	0x33, 0x38, 0x34, 0x1f, 0x43, 0x86, 0x44, 0x6c, 0xb4, 0x18, 0xc2, 0x41, 0x6e, 0xf1, 0x9c, 0xb1,
	0xbb, 0x3d, 0x5c, 0xc7, 0x7c, 0x59, 0x82, 0xd1, 0xea, 0x1f, 0x42, 0xc7, 0xaa, 0xe7, 0x3b, 0x90,
	0xcb, 0x9f, 0xb8, 0xae, 0x8c, 0xb0, 0x9c, 0xf1, 0x9e, 0x63, 0x1f, 0xbd, 0x91, 0xfb, 0x53, 0x78,
	0x6c, 0x3e, 0x7e, 0xfe, 0x3d, 0x43, 0x71, 0xc5, 0xc8, 0x12, 0x85, 0x5f, 0xaf, 0x07, 0xd1, 0x94,
	0x01, 0x74, 0xe6, 0x66, 0x91, 0x53, 0x76, 0x06, 0x36, 0x18, 0x5e, 0xba, 0x0a, 0x5e, 0x2e, 0x96,
	0x77, 0x8c, 0x7b, 0xd0, 0x49, 0xf4, 0xcf, 0x71, 0x5e, 0xf4, 0x3e, 0x74, 0x6d, 0xfe, 0x38, 0xef,
	0xd5, 0x3e, 0x74, 0x23, 0x4e, 0xb3, 0xeb, 0xe5, 0x1c, 0x5d, 0xb7, 0x4e, 0x8a, 0x4c, 0xd6, 0x4b,
	0xdb, 0x26, 0xba, 0x2e, 0xad, 0x74, 0x8f, 0x60, 0x2f, 0xdf, 0xd8, 0x2b, 0x12, 0xbd, 0xd5, 0xaa,
	0x3d, 0x68, 0x24, 0x2b, 0x23, 0xcf, 0xef, 0xc7, 0x35, 0xd7, 0x21, 0xb4, 0x12, 0xce, 0x57, 0xbb,
	0xd2, 0x1b, 0x8c, 0x15, 0xa6, 0x43, 0x9e, 0xcd, 0x68, 0x12, 0xbe, 0x80, 0x7d, 0x03, 0xff, 0x45,
	0xe2, 0x85, 0xc6, 0x14, 0xf9, 0xdc, 0x26, 0xd9, 0xda, 0x1f, 0x42, 0x2b, 0xe2, 0x8b, 0x2c, 0x1f,
	0xb3, 0x41, 0x21, 0xb7, 0xa0, 0x55, 0x2b, 0x6a, 0x7d, 0xeb, 0x8c, 0x4e, 0x91, 0xb1, 0x7f, 0x2d,
	0x36, 0x29, 0x26, 0x6b, 0xb5, 0x23, 0x78, 0x20, 0xf3, 0x75, 0x89, 0x62, 0xff, 0x63, 0xe8, 0x26,
	0xa8, 0x6c, 0xb8, 0xee, 0x17, 0xf4, 0x1c, 0x1e, 0xbe, 0x26, 0x52, 0x4d, 0x30, 0xe2, 0x59, 0xe6,
	0x15, 0xb3, 0x07, 0x1d, 0x89, 0x52, 0x52, 0x9e, 0x99, 0xdc, 0x07, 0xe1, 0x37, 0x6e, 0xa6, 0x5f,
	0xa5, 0x73, 0xc6, 0xdf, 0xd1, 0x75, 0x89, 0x0c, 0x23, 0x95, 0x77, 0x3d, 0x14, 0x25, 0xa9, 0xda,
	0xc0, 0x13, 0x68, 0x26, 0x74, 0xa6, 0x4a, 0x3a, 0xa3, 0x43, 0x11, 0x91, 0x2a, 0xa8, 0xfb, 0xa1,
	0xc7, 0xd0, 0x13, 0x18, 0x89, 0x05, 0x55, 0xd7, 0x34, 0xb5, 0x63, 0xd4, 0xd0, 0x55, 0xcc, 0x04,
	0xe2, 0x30, 0x53, 0x41, 0xd3, 0x68, 0x9e, 0xb9, 0xf6, 0x58, 0xb5, 0x37, 0xb7, 0xdb, 0x0d, 0x68,
	0xf8, 0x77, 0xad, 0x90, 0xa7, 0xeb, 0x5c, 0x87, 0xd5, 0xf2, 0x3b, 0x87, 0xca, 0xa1, 0xa0, 0xca,
	0xa4, 0x75, 0xef, 0x10, 0x6f, 0x6e, 0x6d, 0xc7, 0x74, 0x73, 0xec, 0x9f, 0x57, 0x7f, 0xcc, 0x83,
	0x66, 0xb5, 0xc1, 0x96, 0x1f, 0x0a, 0xa0, 0x21, 0x50, 0x06, 0x6d, 0x7f, 0x5e, 0x7f, 0x70, 0xb7,
	0x94, 0x2d, 0xee, 0xa5, 0x40, 0x12, 0xab, 0x1b, 0xc1, 0x17, 0xc9, 0xcd, 0x96, 0xf6, 0xfe, 0xaa,
	0x55, 0x32, 0x94, 0x1b, 0x5d, 0x37, 0x56, 0xf7, 0x8d, 0x35, 0xaa, 0x8d, 0x35, 0x2b, 0x8d, 0xf9,
	0x96, 0xd7, 0xcf, 0xf5, 0x8f, 0x84, 0x32, 0xef, 0x5c, 0x7f, 0x7e, 0x3f, 0xae, 0x6b, 0x3d, 0x80,
	0x56, 0x4a, 0x28, 0xcb, 0xcf, 0x75, 0x6b, 0xa0, 0x03, 0xe1, 0x17, 0x0e, 0x38, 0x42, 0x56, 0x46,
	0xa4, 0x17, 0xa9, 0x3b, 0x64, 0x8d, 0x95, 0xaa, 0x03, 0x6b, 0x56, 0x17, 0xaf, 0x99, 0xf8, 0x99,
	0x7b, 0x49, 0x26, 0x18, 0x21, 0xbd, 0xc5, 0x73, 0xa5, 0x48, 0x74, 0x93, 0x62, 0xa6, 0x36, 0xd3,
	0x7e, 0x5f, 0x95, 0x66, 0x5f, 0xc1, 0x1e, 0x59, 0xfd, 0x28, 0xbd, 0x94, 0x4e, 0xdc, 0x04, 0x4e,
	0x90, 0xc4, 0xef, 0xf6, 0x70, 0xe2, 0x3c, 0x4c, 0x51, 0x4d, 0x69, 0xe2, 0x9f, 0xe3, 0x1d, 0x68,
	0x4a, 0x9a, 0xe4, 0x87, 0x78, 0x0d, 0x3d, 0x8e, 0x78, 0x29, 0x9a, 0x46, 0xee, 0xc8, 0xb7, 0xd6,
	0xd1, 0x3f, 0x91, 0x14, 0xcb, 0xd0, 0x19, 0x49, 0xd1, 0x71, 0x5f, 0xc1, 0x47, 0xab, 0xbb, 0xd7,
	0x1e, 0xf1, 0x39, 0x46, 0x94, 0x30, 0xaa, 0x96, 0x5b, 0xbe, 0x0e, 0xbb, 0xd0, 0x96, 0x8c, 0xeb,
	0x7b, 0xc3, 0xde, 0x7a, 0xbf, 0x56, 0x33, 0x96, 0x4f, 0xeb, 0x67, 0x00, 0x72, 0x05, 0x71, 0x77,
	0xc7, 0xa3, 0x41, 0x31, 0x37, 0x9c, 0xc2, 0x91, 0xbd, 0xba, 0xe7, 0x31, 0x51, 0xf8, 0x3f, 0x15,
	0xfb, 0xe7, 0x46, 0xd2, 0xff, 0x52, 0xaf, 0x9e, 0x19, 0xf3, 0xac, 0x58, 0xea, 0x92, 0x43, 0x17,
	0x3e, 0x75, 0x0f, 0xf8, 0x88, 0x50, 0xb6, 0xd4, 0x73, 0x30, 0xce, 0x86, 0xa7, 0x43, 0xcf, 0x46,
	0x78, 0xe9, 0xe3, 0xa6, 0x25, 0x38, 0xad, 0x28, 0x4d, 0x34, 0x7f, 0x3d, 0x3c, 0xc5, 0x33, 0x77,
	0xa7, 0x4f, 0x30, 0xc5, 0x78, 0x83, 0xa4, 0x1e, 0x92, 0x98, 0x28, 0xe2, 0x86, 0xe4, 0x6d, 0x49,
	0xda, 0xfb, 0x55, 0xb0, 0xc5, 0xae, 0xbc, 0x70, 0x6e, 0xaf, 0xb9, 0x22, 0x6c, 0x43, 0x89, 0x7d,
	0x80, 0x44, 0x90, 0x2c, 0x36, 0x38, 0x37, 0xfb, 0x97, 0x7e, 0xee, 0xfb, 0xd5, 0xf9, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x92, 0xb8, 0x57, 0x3e, 0xb0, 0x0b, 0x00, 0x00,
}
